###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: avaliacaodockerlaravelvuejs-mysql
      working_dir: /application
      volumes:
        - ./avaliacaosell2brazil:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_DATABASE=avaliacao
        - MYSQL_USER=appuser
        - MYSQL_PASSWORD=apppassword
      ports:
        - "8890:3306"

    webserver:
      image: nginx:alpine
      container_name: avaliacaodockerlaravelvuejs-webserver
      working_dir: /application
      volumes:
          - ./avaliacaosell2brazil:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: avaliacaodockerlaravelvuejs-php-fpm
      working_dir: /application
      volumes:
        - ./avaliacaosell2brazil:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

